apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohanlearning
  labels:
    app: rohanlearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rohanlearning
  template:
    metadata:
      labels:
        app: rohanlearning
    spec:
      containers:
        - name: test
          image: 274127640471.dkr.ecr.us-east-2.amazonaws.com/testrepo:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080