name: Build with Maven

env:
    REPOSITORY: testrepo
    IMAGE_TAG: 1.2
    AWS_REGION: 'us-east-1'
    KS_CLUSTER_NAME: 'my-eks-cluster3'
on:
  push:
    branches: [ main ]  # Change "main" to your main branch name if different
  pull_request:  # Optional: Trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Or another desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code from the repository

      - name: Set up JDK 17  # Change version if needed
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package -DskipTests  # Optionally add -DskipTests to skip tests

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
         version: 'v1.24.0' # default is latest stable
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
      - name: Update kube config
        run: aws eks update-kubeconfig --name $KS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        run: |
            kubectl apply -f deployment.yaml